-- Migration: Add security_audit_json column
ALTER TABLE servers ADD COLUMN security_audit_json TEXT;

UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":56,"auditDate":"2026-05-22","auditorNotes":"Requires MindsDB API key for cloud instance. Data queries routed to MindsDB cloud. Local self-hosted option available."}' WHERE id = 'mindsdb-mcp';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"shell_strings","dataResidency":"local_only","auditScore":52,"auditDate":"2026-05-22","auditorNotes":"Server management tool. Executes shell commands for panel operations. API key for 1Panel REST API. Data stays local."}' WHERE id = 'panel-1panel';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"Pure local browser automation via Playwright API. No auth needed for stdio transport. All data stays on local machine."}' WHERE id = 'playwright-browser-automation';
UPDATE servers SET security_audit_json = '{"transport":"sse_http","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":49,"auditDate":"2026-05-22","auditorNotes":"SSE transport to Upstash cloud. Static API key authentication. Queries external documentation APIs. Data flows to/from cloud."}' WHERE id = 'upstash-context7';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"cloud","auditScore":46,"auditDate":"2026-05-22","auditorNotes":"Stdio transport but fetches documentation from remote web sources. No authentication required for server itself. Outbound cloud data flow."}' WHERE id = 'mastra-docs';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"OAuth2","tokenLifecycle":"short-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":82,"auditDate":"2026-05-22","auditorNotes":"Official GitHub server. Supports OAuth2 flow with short-lived access tokens + refresh. GitHub PAT also supported (long-lived). Parameterized API calls. Data flows to GitHub cloud."}' WHERE id = 'github-official-mcp-new';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"Microsoft official Playwright MCP. Pure local browser automation. No auth. Parameterized Playwright API. Data stays local."}' WHERE id = 'microsoft-playwright-mcp';
UPDATE servers SET security_audit_json = '{"transport":"both","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":49,"auditDate":"2026-05-22","auditorNotes":"Supports stdio and SSE. API key auth with long-lived tokens. Integrates with 280+ services. Data flows through Activepieces cloud platform."}' WHERE id = 'activepieces-mcp';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"MCP server framework (not a standalone server). Provides Python SDK for building servers. No built-in auth. Local-only by default. Parameterized tool definitions."}' WHERE id = 'fastmcp';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":56,"auditDate":"2026-05-22","auditorNotes":"Reads Figma design data via Figma Personal Access Token (long-lived). Stdio transport. Data fetched from Figma cloud APIs."}' WHERE id = 'figma-context-mcp';
UPDATE servers SET security_audit_json = '{"transport":"sse_http","authMethod":"OAuth2","tokenLifecycle":"short-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":77,"auditDate":"2026-05-22","auditorNotes":"Google official. SSE transport for remote deployment. OAuth2 with short-lived access tokens. Data flows through Google Cloud APIs."}' WHERE id = 'googleapis-genai-toolbox';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"AI-powered code analysis. Stdio transport. No auth. Operates on local codebase. Data stays on local machine."}' WHERE id = 'serena-mcp';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"MCP client framework for Python agents. Stdio transport. No built-in auth. Local-only by design. Parameterized tool calls."}' WHERE id = 'mcp-use';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"mixed","dataResidency":"local_only","auditScore":50,"auditDate":"2026-05-22","auditorNotes":"Multi-tool MCP server. Stdio transport. No auth. Some tools use shell commands (mixed input handling). Data stays local."}' WHERE id = 'zen-mcp-server';
UPDATE servers SET security_audit_json = '{"transport":"both","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":45,"auditDate":"2026-05-22","auditorNotes":"Debugging/inspection tool. SSE for web UI + stdio for MCP protocol. No auth (dev tool). Parameterized. Local-only data."}' WHERE id = 'mcp-inspector';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"Reverse engineering with Ghidra. Stdio transport. No auth. Operates on local binary files. Data stays local."}' WHERE id = 'ghidra-mcp';
UPDATE servers SET security_audit_json = '{"transport":"both","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":49,"auditDate":"2026-05-22","auditorNotes":"AWS official MCP servers. Supports stdio and SSE. AWS access keys (long-lived IAM credentials). Parameterized API calls. Data flows through AWS cloud."}' WHERE id = 'awslabs-mcp-official';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"None","tokenLifecycle":"N/A","inputHandling":"parameterized","dataResidency":"local_only","auditScore":60,"auditDate":"2026-05-22","auditorNotes":"Chrome DevTools Protocol integration. Stdio transport. No auth. Controls local Chrome browser. Data stays local."}' WHERE id = 'mcp-chrome-hangwin';
UPDATE servers SET security_audit_json = '{"transport":"stdio","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":56,"auditDate":"2026-05-22","auditorNotes":"WhatsApp Web integration. Stdio transport. Uses WhatsApp session credentials (long-lived). Data flows through WhatsApp cloud. Parameterized message API."}' WHERE id = 'whatsapp-mcp';
UPDATE servers SET security_audit_json = '{"transport":"both","authMethod":"API Key","tokenLifecycle":"long-lived","inputHandling":"parameterized","dataResidency":"cloud","auditScore":49,"auditDate":"2026-05-22","auditorNotes":"GitHub repository management. Supports stdio and SSE. GitHub PAT (long-lived). Parameterized Git operations. Data flows through GitHub API."}' WHERE id = 'git-mcp-idosal';

-- Done: 20 servers audited